radianHub/People-Incorporated

- force-app/main/default/objects/Opportunity/fields/Actualized_Stock_Sold_Value__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Valuation_At_Time_Of_Giving__c.field-meta.xml
> [DevOps Center] Merge WI-010933 to Integration

- force-app/main/default/objects/Account/fields/Total_Volunteer_Hours__c.field-meta.xml
- force-app/main/default/objects/Opportunity/businessProcesses/Sponsorship.businessProcess-meta.xml
- force-app/main/default/objects/Opportunity/fields/Acknowledgement_Letter__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Acknowledgement__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Constituency__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/EA_Team_Assignment__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Gift_Code__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Gift_ID__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Gift_Status__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Needs_Receipt__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Posted_Date__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Posted__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Receipt_Amount__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Receipt_Status__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Reference_Date__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/Reference_Number__c.field-meta.xml
- force-app/main/default/objects/Opportunity/recordTypes/Sponsorship.recordType-meta.xml
> [DevOps Center] Merge WI-011007 to Integration

- force-app/main/default/customindex/Contact.BB_ID__c.indx-meta.xml
- force-app/main/default/objects/Contact/fields/Annual_Report_Listing__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/BB_ID__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Constituent_Id__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Date_of_Birth__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Maiden_Name__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Marital_Status__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Middle_Name__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Nickname__c.field-meta.xml
> [DevOps Center] Merge WI-011021 to Integration

- force-app/main/default/flows/Volunteer_Hours_Calculator.flow-meta.xml
> [DevOps Center] Merge WI-011054 to Integration

- force-app/main/default/flows/Volunteer_Hours_Calculator.flow-meta.xml
> [DevOps Center] Merge WI-011056 to Integration

- force-app/main/default/flexipages/Acknowledgement_Template.flexipage-meta.xml
- force-app/main/default/permissionsets/Lightning_Email_Builder.permissionset-meta.xml
> [DevOps Center] Merge WI-011062 to Integration

- force-app/main/default/reports/PeopleIncorporated/New_Recurring_Donations_Report_gO5.report-meta.xml
> [DevOps Center] Merge WI-011065 to Integration

- force-app/main/default/reports/PeopleIncorporated/Opportunities_Totals_and_Averages_1Xo.report-meta.xml
> [DevOps Center] Merge WI-011066 to Integration

- force-app/main/default/objects/Opportunity/fields/Grant_Loss_Reason__c.field-meta.xml
- force-app/main/default/objects/Opportunity/validationRules/Require_Closed_Lost_Reason.validationRule-meta.xml
> [DevOps Center] Merge WI-011068 to Integration

- force-app/main/default/flows/Update_Opportunity_When_Stock_is_Relized.flow-meta.xml
> [DevOps Center] Merge WI-011069 to Integration

- force-app/main/default/objects/Opportunity/listViews/Team_2.listView-meta.xml
> [DevOps Center] Merge WI-011077 to Integration

- force-app/main/default/featureParameters/npsp__IsEnabled_RecurringDonations2.featureParameterBoolean-meta.xml
> [DevOps Center] Merge WI-011078 to Integration

- force-app/main/default/approvalProcesses/Opportunity.Grant_Approval_Process.approvalProcess-meta.xml
- force-app/main/default/groups/Leadership_Team.group-meta.xml
- force-app/main/default/standardValueSets/OpportunityStage.standardValueSet-meta.xml
- force-app/main/default/workflows/Opportunity.workflow-meta.xml
> [DevOps Center] Merge WI-011088 to Integration

- force-app/main/default/classes/ClosedWonOpportunities.cls
- force-app/main/default/classes/ClosedWonOpportunities.cls-meta.xml
- force-app/main/default/components/ClosedWonOpportunitiesEmailTemplate.component
- force-app/main/default/components/ClosedWonOpportunitiesEmailTemplate.component-meta.xml
- force-app/main/default/pages/ClosedWonOpportunities.page
- force-app/main/default/pages/ClosedWonOpportunities.page-meta.xml
- force-app/main/default/pages/EmailDoc.page
- force-app/main/default/pages/EmailDoc.page-meta.xml
> [DevOps Center] Merge WI-011098 to Integration

- force-app/main/default/customMetadata/Donation_Amount.One_Time.md-meta.xml
- force-app/main/default/customMetadata/Donation_Amount.Recurring.md-meta.xml
- force-app/main/default/lwc/donationSelection/donationSelection.js
- manifest/package.xml
> [DevOps Center] Merge WI-011105 to Integration

- force-app/main/default/classes/OpportunityHandler.cls
- force-app/main/default/classes/OpportunityHandlerTest.cls
- force-app/main/default/classes/OpportunityHandlerTest.cls-meta.xml
- force-app/main/default/customMetadata/Acknowledgement_Letter.AckLetter.md-meta.xml
- force-app/main/default/objects/Acknowledgement_Letter__mdt/Acknowledgement_Letter__mdt.object-meta.xml
- force-app/main/default/objects/Acknowledgement_Letter__mdt/fields/Letter__c.field-meta.xml
- force-app/main/default/pages/EmailTemplateGenerator.page
> [DevOps Center] Merge WI-011126 to Integration

- force-app/main/default/pages/EmailDoc.page-meta.xml
> [DevOps Center] Merge WI-011125 to Integration

- force-app/main/default/objects/Opportunity/validationRules/Require_Closed_Lost_Reason.validationRule-meta.xml
> [DevOps Center] Merge WI-011127 to Integration

- force-app/main/default/objects/Opportunity/validationRules/Require_Closed_Lost_Reason.validationRule-meta.xml
> [DevOps Center] Merge WI-011127 to UAT

- force-app/main/default/pages/EmailDoc.page
> [DevOps Center] Merge WI-011128 to Integration

- force-app/main/default/objects/Opportunity/validationRules/Require_Closed_Lost_Reason.validationRule-meta.xml
- force-app/main/default/pages/EmailDoc.page
DevOps Center created this pull request for DevOps Center use only. Due to the potential for data corruption, DO NOT MERGE this pull request in GitHub.
> [DO NOT MERGE] For DevOps Center use only - Integration to UAT

- force-app/main/default/flows/Email_Alert_When_Grant_Is_Won.flow-meta.xml
- force-app/main/default/flows/Opportunity_After_Update.flow-meta.xml
> [DevOps Center] Merge WI-011129 to Integration

- force-app/main/default/flows/Opportunity_After_Update.flow-meta.xml
> [DevOps Center] Merge WI-011130 to Integration

- force-app/main/default/flows/Update_Opportunity_When_Stock_is_Relized.flow-meta.xml
- force-app/main/default/layouts/Opportunity-Stock%2FBond Donation Layout.layout-meta.xml
- force-app/main/default/objects/Opportunity/businessProcesses/Stock%2FBond Donation.businessProcess-meta.xml
- force-app/main/default/objects/Opportunity/validationRules/Require_Actualized_Value.validationRule-meta.xml
- force-app/main/default/standardValueSets/OpportunityStage.standardValueSet-meta.xml
> [DevOps Center] Merge WI-011131 to Integration

- force-app/main/default/email/People_Incorporated_Email_Templates/Year_End_Statement_Email.email
- force-app/main/default/email/People_Incorporated_Email_Templates/Year_End_Statement_Email.email-meta.xml
> [DevOps Center] Merge WI-011133 to Integration

- force-app/main/default/objects/Opportunity/fields/Stripe_Payment_Fees__c.field-meta.xml
- force-app/main/default/objects/Opportunity/fields/True_Payment_Amount_Received__c.field-meta.xml
- force-app/main/default/objects/npe01__OppPayment__c/fields/Stripe_Fee__c.field-meta.xml
- force-app/main/default/objects/npe01__OppPayment__c/fields/True_Amount__c.field-meta.xml
> [DevOps Center] Merge WI-011340 to Integration

- force-app/main/default/objects/Case/Case.object-meta.xml
- force-app/main/default/objects/Case/fields/Closed_Reason__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Insurance_Status__c.field-meta.xml
- force-app/main/default/objects/Case/fields/Length_of_Stay__c.field-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Client.recordType-meta.xml
> [DevOps Center] Merge WI-011380 to UAT

- force-app/main/default/objects/Case/businessProcesses/ARMHS.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Care Coordination.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Case Referral Process.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Case Support Process.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Crisis.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Groups.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/IRTS.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Long Term Residential.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/School Based.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Skills.businessProcess-meta.xml
- force-app/main/default/standardValueSets/CaseStatus.standardValueSet-meta.xml
> [DevOps Center] Merge WI-011381 to UAT

- force-app/main/default/objects/Case/fields/Closed_Reason__c.field-meta.xml
> [DevOps Center] Merge WI-011385 to UAT

- force-app/main/default/globalValueSets/Primary_Contact_Person.globalValueSet-meta.xml
> [DevOps Center] Merge WI-011389 to UAT

- force-app/main/default/objects/Case/businessProcesses/ARMHS.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Care Coordination.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Case Referral Process.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Case Support Process.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Crisis.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Groups.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/IRTS.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Long Term Residential.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/School Based.businessProcess-meta.xml
- force-app/main/default/objects/Case/businessProcesses/Skills.businessProcess-meta.xml
- force-app/main/default/standardValueSets/CaseStatus.standardValueSet-meta.xml
> [DevOps Center] Merge WI-011381 to Staging

- force-app/main/default/objects/Case/fields/Preferred_Name__c.field-meta.xml
> [DevOps Center] Merge WI-011397 to UAT

- force-app/main/default/objects/Contact/fields/Date_of_Last_Comp__c.field-meta.xml
> [DevOps Center] Merge WI-011399 to UAT

- force-app/main/default/objects/Contact/fields/Date_of_Last_Comp__c.field-meta.xml
> [DevOps Center] Merge WI-011399 to Staging
